hot_wallets.rb: process with pid 16903 started.
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:97:in `call': ERR unknown command 'setex' (Redis::CommandError)
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:691:in `block in setex'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	from /home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:690:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/interface.rb:17:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `block in setex'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/cache.rb:519:in `instrument'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/app/models/currency.rb:33:in `refresh_balance'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:19:in `block in <top (required)>'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:18:in `each'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/hot_wallets_ctl:6:in `<main>'
hot_wallets.rb: process with pid 22258 started.
hot_wallets.rb: process with pid 3435 started.
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:97:in `call': ERR unknown command 'setex' (Redis::CommandError)
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:691:in `block in setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	from /home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:690:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/interface.rb:17:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `block in setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.2/lib/active_support/cache.rb:519:in `instrument'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/app/models/currency.rb:33:in `refresh_balance'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:19:in `block in <top (required)>'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:18:in `each'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/hot_wallets_ctl:6:in `<main>'
hot_wallets.rb: process with pid 25352 started.
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:97:in `call': ERR unknown command 'setex' (Redis::CommandError)
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:691:in `block in setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
	from /home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:690:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/interface.rb:17:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `block in setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:13:in `setex'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.2/lib/active_support/cache.rb:519:in `instrument'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/app/models/currency.rb:33:in `refresh_balance'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:19:in `block in <top (required)>'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:18:in `each'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/hot_wallets.rb:18:in `<top (required)>'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/hot_wallets_ctl:6:in `<main>'
