# Logfile created on 2014-07-10 14:10:49 by logger.rb/44203
I, [2014-07-10T14:10:50.027610 #16701]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2014-07-10T14:10:50.032314 #16701] ERROR -- : cannot load such file -- 2.1/bcrypt_ext (LoadError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `block in load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bcrypt-ruby-3.1.2/lib/bcrypt.rb:14:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `block in load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/secure_password.rb:1:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:8:in `<class:ActiveRecord>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:6:in `<module:Models>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:5:in `<module:Identity>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:4:in `<module:OmniAuth>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:3:in `<top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/app/models/identity.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:424:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:424:in `block in load_file'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:423:in `load_file'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:324:in `require_or_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:289:in `depend_on'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:207:in `require_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:464:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:464:in `block in eager_load!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:462:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:462:in `eager_load!'
/home/yuva/Desktop/arvind/peatio/peatio-master/config/routes.rb:4:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `execute'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:6:in `execute_if_updated'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `call'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/yuva/Desktop/arvind/peatio/peatio-master/config/environment.rb:5:in `<top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:9:in `require'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:9:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-07-10T14:10:50.037990 #16701]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-07-10T14:10:50.038122 #16701] ERROR -- : exception reentered (fatal)

E, [2014-07-10T14:10:50.045280 #16701] ERROR -- : stream closed (IOError)

E, [2014-07-10T14:10:50.045510 #16701] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-07-10T14:10:50.045599 #16701] ERROR -- : stack level too deep (SystemStackError)

E, [2014-07-10T14:10:50.057516 #16701] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2014-07-10T14:10:50.148952 #16701] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `new'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `new'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `exception_log'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:165:in `block in start_load'
E, [2014-07-10T14:10:50.161268 #16701] ERROR -- : No such file or directory @ rb_sysopen - /home/yuva/Desktop/arvind/peatio/peatio-master/log/k.rb.log (Errno::ENOENT)
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `new'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `new'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:353:in `exception_log'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:165:in `block in start_load'
E, [2014-07-10T14:10:50.161687 #16701] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:31:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.172113 #16701] ERROR -- : undefined method `created_at' for nil:NilClass (NoMethodError)
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:31:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.174849 #16701] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.185137 #16701] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.185381 #16701] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:81:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.185636 #16701] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:81:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.185803 #16701] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.186057 #16701] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.267926 #16701] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `block in load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bcrypt-ruby-3.1.2/lib/bcrypt.rb:14:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `block in load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/secure_password.rb:1:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:8:in `<class:ActiveRecord>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:6:in `<module:Models>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:5:in `<module:Identity>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:4:in `<module:OmniAuth>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:3:in `<top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/app/models/identity.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:424:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:424:in `block in load_file'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:423:in `load_file'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:324:in `require_or_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:289:in `depend_on'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:207:in `require_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:464:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:464:in `block in eager_load!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:462:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:462:in `eager_load!'
/home/yuva/Desktop/arvind/peatio/peatio-master/config/routes.rb:4:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `execute'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:6:in `execute_if_updated'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `call'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/yuva/Desktop/arvind/peatio/peatio-master/config/environment.rb:5:in `<top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:9:in `require'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:9:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T14:10:50.277170 #16701] ERROR -- : cannot load such file -- 2.1/bcrypt_ext (LoadError)
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `block in load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/bcrypt-ruby-3.1.2/lib/bcrypt.rb:14:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `block in load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:212:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/secure_password.rb:1:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:8:in `<class:ActiveRecord>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:6:in `<module:Models>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:5:in `<module:Identity>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:4:in `<module:OmniAuth>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/omniauth-identity-1.1.1/lib/omniauth/identity/models/active_record.rb:3:in `<top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/app/models/identity.rb:17:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:424:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:424:in `block in load_file'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:616:in `new_constants_in'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:423:in `load_file'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:324:in `require_or_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:289:in `depend_on'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:207:in `require_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:464:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:464:in `block in eager_load!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:462:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/engine.rb:462:in `eager_load!'
/home/yuva/Desktop/arvind/peatio/peatio-master/config/routes.rb:4:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `execute'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:6:in `execute_if_updated'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `call'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/home/yuva/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/yuva/Desktop/arvind/peatio/peatio-master/config/environment.rb:5:in `<top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:9:in `require'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:9:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-07-10T18:08:43.841410 #2958]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2014-07-10T18:08:44.091828 #2958] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
I, [2014-07-10T18:08:44.092023 #2958]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-07-10T18:08:44.092124 #2958] ERROR -- : exception reentered (fatal)

E, [2014-07-10T18:08:44.099967 #2958] ERROR -- : stream closed (IOError)

E, [2014-07-10T18:08:44.100126 #2958] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-07-10T18:08:44.100199 #2958] ERROR -- : stack level too deep (SystemStackError)

E, [2014-07-10T18:08:44.142477 #2958] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

E, [2014-07-10T18:08:44.239896 #2958] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:31:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T18:08:44.240032 #2958] ERROR -- : undefined method `created_at' for nil:NilClass (NoMethodError)
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:31:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T18:08:44.252194 #2958] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T18:08:44.252406 #2958] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:81:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T18:08:44.252541 #2958] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:81:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T18:08:44.252625 #2958] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T18:08:44.252755 #2958] ERROR -- : no such frame (ArgumentError)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `frame_binding'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:25:in `block (2 levels) in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `loop'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:23:in `block in callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `open'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/better_errors-1.1.0/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
E, [2014-07-10T18:08:44.252860 #2958] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1117:in `block in lindex'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/yuva/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/redis-3.0.7/lib/redis.rb:1116:in `lindex'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:26:in `next_ts'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:82:in `block in <top (required)>'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `each'
/home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/k.rb:81:in `<top (required)>'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/k_ctl:6:in `<main>'
